/*
sS <- 's' sS sS /     // right-recursive, but with an null (epsilon) recursion path
pS <- ('p')*          // pS as iterative

pSr <- 'p' pSr /      // pS rewritten as right-recursive, no null path (Ford 4.1)

pSri <- (pSr)*        // pSr* rewritten as interative

pSrr <- pSr pSrr /    // pSri rewritten as right-recursive, with null path

pSi <- (pSr)*         // pS1 rewritten as iterative, with null path

N <- [1-9] [0-9]*
F <- ( "e" ) | N
T <- T '*' F / F
E <- E '+' T / E '-' T / T 
FooBar <- 'foo' FooBar 'bar' | 'foo' '|' 'bar'
*/
Z <- Z
/*
A <- (A 'a')+ |
C <- (C 'c')*  
B <- (A | C) 'b' !.
*/