DEFINE ((
	(MEMBER (LAMBDA (A X) (COND ((NULL X) F)
		((EQ A (CAR X))T) (T (MEMBER A (CDR X))) )))
	(UNION (LAMBDA (X Y) (COND ((NULL X) Y) ((MEMBER
		(CAR X) Y) (UNION (CDR X) Y)) (T (CONS (CAR X)
		(UNION (CDR X) Y))) )))
	(INTERSECTION (LAMBDA (X Y) (COND ((NULL X) NIL)
		((MEMBER (CAR X) Y) (CONS (CAR X) (INTERSECTION
		(CDR X) Y))) (T (INTERSECTION (CDR X) Y)) )))
))
INTERSECTION ((A1 A2 A3) (A1 A3 A5))
UNION ((X Y Z) (U V W X))


	