
X
CAR
(CAR X)
(QUOTE T)
(A.NIL)
(A.(B.(C.NIL)))
(QUOTE.(THIS IS A (LIST.NIL)))(LABEL FF (LAMBDA (X) (COND
	((ATOM X) X)
	((QUOTE T) (FF (CAR X))))))
(FF (CAR X))
(COND ((ATOM X) X)
	((QUOTE T) (FF (CAR X))))