COMMENT (THIS AN OTHER EXAMPLES ARE FROM THE LISP 1 POINT 5 PROGRAMMERS MANUAL BY JOHN MCCARTHY ET AL)
X
CAR
(CAR X)
(QUOTE T)
(FF (CAR X))
(COND ((ATOM X) X)
	((QUOTE T) (FF (CAR X))))
(LABEL FF (LAMBDA (X) (COND
	((ATOM X) X)
	((QUOTE T) (FF (CAR X))))))
(A.NIL)
(A.(B.(C.NIL)))
(QUOTE.(THIS IS A (LIST.NIL)))